FROM postgres:18.6-trixie

RUN apt-get update \
    && apt-get install --yes --no-install-recommends pgbackrest=2.55.1-1 \
    && rm -rf /var/lib/apt/lists/*

COPY pgbackrest.conf /etc/pgbackrest/pgbackrest.conf
